github.com:
    users:
        almostbinary:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: almostbinary
